version: '3.9'
services:
  service_node_js:
    image: server_node_js
    container_name: server_node_js
    build:
        context: .
        dockerfile: Dockerfile
    command: npm run start:dev
    restart: always
    depends_on:
      - data_base_postgres
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT = ${PORT}
      - DATABASE_URL = postgresql://

  data_base_postgres:
    image: data_base_postgres
    container_name: data_base_postgres
    build:
      dockerfile: ./dataBase/Dockerfile
      context: .
    volumes:
      - postgres_data_base:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql/postgresql.log
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

networks:
  default:
    driver: bridge

volumes:
  postgres_logs:
  postgres_data_base: